[package]
name = "starrail-unlock-rs"
version = "0.1.1"
edition = "2021"

[profile.release]
opt-level = 3
strip = true
lto = "thin"

[dependencies]
serde_json = "1.0.96"
winreg = "0.50.0"

[dependencies.native-dialog]
version = "0.6.3"
features = ["windows_dpi_awareness", "windows_visual_styles"]
